// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmANLnAQIkw8wVT5R8E4yaiU2sBIBHTdY',
    appId: '1:448465555804:web:b9b548cec2e97ec949f199',
    messagingSenderId: '448465555804',
    projectId: 'fir-testing-93538',
    authDomain: 'fir-testing-93538.firebaseapp.com',
    databaseURL: 'https://fir-testing-93538.firebaseio.com',
    storageBucket: 'fir-testing-93538.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwKWFpt9068ojgGC_xcF77roKvA7EvXo',
    appId: '1:448465555804:android:1c96af11911f1cdf49f199',
    messagingSenderId: '448465555804',
    projectId: 'fir-testing-93538',
    databaseURL: 'https://fir-testing-93538.firebaseio.com',
    storageBucket: 'fir-testing-93538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_gR_9uEkG5N5NPYDWe9EbDWThAwRMS4',
    appId: '1:448465555804:ios:a9ee337bc6791c4749f199',
    messagingSenderId: '448465555804',
    projectId: 'fir-testing-93538',
    databaseURL: 'https://fir-testing-93538.firebaseio.com',
    storageBucket: 'fir-testing-93538.appspot.com',
    androidClientId: '448465555804-mca3rsfjrjq837h26u5iur7hbttssvn4.apps.googleusercontent.com',
    iosClientId: '448465555804-kv364rij2qs7j4u71egdd5teufl27aer.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseIntegrations',
  );
}
